from tkinter import *
window=Tk()
window.title("welcome")
window.geometry("400x500")
window.resizable(False,False)
window.configure(background="#8c6d74")
window.attributes("-topmost",True)
window.attributes("-alpha",0.9)
window.iconbitmap("favicon.ico")
lbl=Label(text="enter first number")
lbl.place(x=20,y=20)
lbn=Label(text="enter second number")
lbn.place(x=20,y=50)
e1=Entry()
e1.place(x=130,y=20)
e2=Entry()
e2.place(x=150,y=51)
btn=Button(text="sum")
btn.place(x=180,y=90)
e3=Entry()
e3.place(x=150,y=130)

window.mainloop()